version: "3"

services:
  loki:
    image: grafana/loki:2.6.1
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    logging:
      driver: json-file

  promtail:
    image: grafana/promtail:2.6.1
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./tmp/:/tmp
    depends_on:
      - loki
    logging:
      driver: json-file

  grafana:
    image: grafana/grafana:9.1.6
    environment:
      GF_LOG_LEVEL: error
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - loki
    logging:
      driver: json-file

  logfile-generator:
    image: busybox
    command: sh /generate-logfile.sh /tmp/logfile.log
    volumes:
      - ./generate-logfile.sh:/generate-logfile.sh
      - ./tmp/:/tmp
    logging:
      driver: json-file
