server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: promtail
  pipeline_stages:
    - regex:
        expression: '^(?P<timestamp>\d+).*$'
    - timestamp:
        source: timestamp
        format: Unix
  static_configs:
    - targets:
        - localhost
      labels:
        job: sametimestamps
        __path__: /tmp/logfile.log

